compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_config_file: config/deepspeed/zero3.json
  deepspeed_hostfile: config/hostfile
  deepspeed_multinode_launcher: pdsh
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 1
main_process_ip: gpu007
main_process_port: 29500
main_training_function: main
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
